// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID          int32              `json:"id"`
	Model       string             `json:"model"`
	UserUuid    uuid.UUID          `json:"user_uuid"`
	UserName    pgtype.Text        `json:"user_name"`
	Action      string             `json:"action"`
	ActionAt    pgtype.Timestamptz `json:"action_at"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
