// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	GetLogByID(ctx context.Context, id int32) (Log, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error)
	ListLogsByModel(ctx context.Context, arg ListLogsByModelParams) ([]Log, error)
	ListLogsByUserUUID(ctx context.Context, arg ListLogsByUserUUIDParams) ([]Log, error)
}

var _ Querier = (*Queries)(nil)
